language: node_js
node_js:
  - 8
branches:
  only:
    - master
    - dev
script:
  - cd functions
  - npm install
  - npm run lint
  - cd ..
deploy:
  - provider: firebase
    token:
      secure: bq61gwzneIfi+MG7ITgAPdTkaDIdk4IDt3GF11GGU0HqK/v8LliyNNY1gkz59bTqImTEruAg/wGFbQm7i3phEAnHbIdmNYQzc32vaFZP6HJ7h7pruh78rOkBqUyCPhNCp/XZDWryyz1xeRPoAdyYW8f9reINvMwtLWU5JsAD1GVY6y/rvweGbkkrDU4Ugwi+1PQ+dIqtMN5l8dXpH61ErPyixSR5wO2djzq8zcFyapzAaRG3Z3ZaWdfRA/NDhfABnoFvOw9jIQxUYJ7rnS1KLGecNW/8B5iqhaB77euo1munuFfA6EQMlPxA/SbF8tkQDH2+0LfRlvAFX4XuK7YU72sSvFX7DuUAHj+wvyzlbOglBstSOJbgEOAu+s+WRiBaCG2SwixgZs6iH3u0bEl5/4WSLD5yKajz+mNQAIHQxm2F2Jv54rw/JAw+WWQnE2SC9O3t+AIqSdAw457W5xBkNPA63y9Uex2xFv6QXg5eQvsZdGmp1PFUoQOOv0/v0WUTISNrdxVCWm5nWohq27UXLYPyWMsyTHBUUrCUieD6RBPi3MYGF8mZa3elTHP+z89o5OsiEkXeYMOHb0hlsGmSXjaL+ho1OKnEcZYgIUeDgWrE7tcFEEtXJVAiiWOp+2zPSD/G3fehWQt8r21XQtRZ0vQcbLMOUFqGbbWpAg9fFfU=
    project: chess-bet-test
    on:
      branch : dev
    skip_cleanup: true
  - provider: firebase
    token:
      secure: bq61gwzneIfi+MG7ITgAPdTkaDIdk4IDt3GF11GGU0HqK/v8LliyNNY1gkz59bTqImTEruAg/wGFbQm7i3phEAnHbIdmNYQzc32vaFZP6HJ7h7pruh78rOkBqUyCPhNCp/XZDWryyz1xeRPoAdyYW8f9reINvMwtLWU5JsAD1GVY6y/rvweGbkkrDU4Ugwi+1PQ+dIqtMN5l8dXpH61ErPyixSR5wO2djzq8zcFyapzAaRG3Z3ZaWdfRA/NDhfABnoFvOw9jIQxUYJ7rnS1KLGecNW/8B5iqhaB77euo1munuFfA6EQMlPxA/SbF8tkQDH2+0LfRlvAFX4XuK7YU72sSvFX7DuUAHj+wvyzlbOglBstSOJbgEOAu+s+WRiBaCG2SwixgZs6iH3u0bEl5/4WSLD5yKajz+mNQAIHQxm2F2Jv54rw/JAw+WWQnE2SC9O3t+AIqSdAw457W5xBkNPA63y9Uex2xFv6QXg5eQvsZdGmp1PFUoQOOv0/v0WUTISNrdxVCWm5nWohq27UXLYPyWMsyTHBUUrCUieD6RBPi3MYGF8mZa3elTHP+z89o5OsiEkXeYMOHb0hlsGmSXjaL+ho1OKnEcZYgIUeDgWrE7tcFEEtXJVAiiWOp+2zPSD/G3fehWQt8r21XQtRZ0vQcbLMOUFqGbbWpAg9fFfU=
    project: chessbet-app-com-v1
    on:
      branch : master
    skip_cleanup: true
notifications:
  slack:
    secure: dtxgZiGXJe76EL3waQAQK/gWgeIXaLnGTKrZrq8S/bUSth9WMrxvfxIn3ql4qDFy2SIxwxo/qDe5Gzsg0e4aKbmZabAIOMN9B2mulWnzP7pcV9ZDavXBRmvNQMD7zxUlY+LP4eVEt6lOsgDatqg4dXWiuayLW8iC1cVrbebkf6aIeL9Or9G4kEcNxrFwjdaACoc7RWDifxtizpwOhC542OzqlUhTv3tGv/IQGiJVg6bEKl5ElnG+B0fVpmVQ2UTbvb/HuHsXlcppJ92k3cPn0oTkJb8Evo/+xvsuVGL4jvBC8WMYvAJ4gMJYsiDzhtJhQGO8r65lcjAvyuqmvvjLtFapyYmyv8WANa08VX3LWVZhBTuAgd4xH4n7ADaATsd7OSCyxOHRRXlxjflVZwYQa6O3ZpQ75Qd9MtzjOGhWwq4628zyKfi/HhNwr1FGvWJXO2WD9ritC1ttb1EvNG7/DAoRUC8uQoDWskOMluF0IO0T+RLeLeQktvkVMR7h51yn+lnOQphlYswpUKVoSDoXuPJIUuqcrRF2XI4gxJ5Wnzbdpb1QBFRvNWvOXL5k4iWfWtj22CBG0muI7GtBPIlN76USRmjrkHBCL41ppCIcpx5bp/cxtarFPCdobt5Wpxe+Dz7xqJGOtYuBGoROD4pymzEewDJFNYr5/39v1IxgsmU=